### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Antsax** [EssKayz/EssKayz-TiraLabra2019K#2]
Projekti ladattiin 15.12.2018 14:44

Ohjelma näyttää olevan hyvässä vaiheessa ja laaja. Luokat on jäsennelty järkevästi oikeisiin kansioihin ja ne seuraavat single-responsibility periaatetta. Erityisesti pisteitä antaisin tekoälyjen määrästä. Ohjelmoija on onnistunut luomaan useita eri tekoälyjä pelille ja ne vaihtuvat pelaajan strategiasta riippuen. Tämä on mielestäni erittäin vaikuttavaa. Tekoäly saattaa hävitä alussa muutaman kerran, mutta mitä enemmän pelataan sitä todennäköisemmin tekoäly voittaa. 

Joidenkin luokkien ymmärtäminen on osoittanut hieman hankalaksi. Esim. MetaStrat -kansiossa on 4 luokkaa, joista 3 ovat tyhjiä (jotka luultavasti täytetään myöhemmässä vaiheessa) ja MetaStrategy luokan tarkoitusta en oikein ymmärrä. Johtunee varmaankin kommenttien puutteesta. Muissa luokissa kommentteja on kuitenkin riittävästi ja ne on hyvin selitetty. Toisaalta jotku luokat voisi ehkä hajoittaa pienempiin kokonaisuuksiin. Esim. voidaanko luoda luokka, jota kaikki tekoälyalgoritmit hyödyntävät?

Testejä ei ole niinkään paljon (lukuunottamatta Stepdefs luokkaa), mutta niitä tuskin tarvitaan vielä tässä vaiheessa. Ohjelma näyttäisi toimivan ilman ongelmia. Ohjelmoija on luultavasti päättänyt jättää testien tekeminen myöhempään ajankohtaan ja keskittyy tällä hetkellä ohjelman tekemiseen, mikä on mielestäni toimiva suunnitelma. En tiedä, pitääkö testiluokkien lopussa olla sana "Test". Vain RunCukesTest -luokassa tämä toteutuu. En ole varma, vaikuttaako tämä testien toimivuuteen, joten en ota kantaa tähän.

Peliä voi pelata suoraan selaimella ja linkki löytyy README:stä, mikä on varsin kätevää.

Kaiken kaikkiaan hieno ohjelma. Se on hyvässä vaiheessa ja toimii mallikkaasti. Hyvää työtä!

**Comment by EssKayz** [comment]
Kiitos palautteesta!

MetaStragetiat ovat tosiaan vielä osittain kehitysvaiheessa, joten sen takia vähän heikohkosti kommentoitua.

Tekoälyalgoritmit hyödyntävät kaikki luokkaa GameAI, jonka metodit kaikki tekoälyt perivät. Sinne voisi toki vielä katsoa saisiko paremmin sinnekkin hajautettua lisää tavaraa.

Testejä tosiaan toistaiseksi lähinnä tuo stepdefs luokka. 
Tämä sen takia, että käytän Selenium Cukes testejä.
Eli toisin sanoen, test/resources/ kansiossa löytyvät .feature tiedostot määrittelevät, että mitä testejä ajetaan.
Jokainen "feature" ajaa siis kaikki ne Skenaariot, mitkä sinne on määritelty - jossa yksi skenaario käytännössä luo ositellun testin.
Ja nämä kaikki testit sitten löytyvät stepdefs luokan sisältä. 

Vähän erillainen ilmiö kun normaalissa JUnit testaamisessa, mutta soveltuu erinomaisesti automaattiseen verkkosivun testaamiseen, sillä Selenium käynnistää oman instanssin Chrome'sta, ja painelee nappuloita samaan tapaan kuin ihminen niitä painelisi. Näin saadaan testattua sekä verkkosivun UI, sekä luokat mitä nappien painelu käyttää :)

Tätäkin pääsee katsomaan ja ihailemaan livenä, jos seuraa TestDocumentation.md tiedoston ohjeita (Toimii Win10, en osaa muista OS sanoa)

Teen vielä JUnit testit erikseen noille omille tietorakenteille, jossa testaan ja vertaan niiden toimintaa valmiisiin tietorakenteisiin.

Mukava kuulla, että ei ollut liian sekavan näköinen, välillä kun itse katson sitä ja näen pingviinin ja elefantin synnyttämän sekasikiö-lapsen <3 .
