### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by heidihas** [EssKayz/EssKayz-TiraLabra2019K#3]
![image](https://user-images.githubusercontent.com/32390965/53237638-da333600-369f-11e9-8b0d-70fd970dfb25.png)

**Comment by EssKayz** [comment]
Kiitos palautteesta!

Ensimmäisenä silmään popsahti tuo Controller luokkaan kohdistuva kommentti. Täytynee itse tarkistaa, mikäli sinne on eksynyt jotakin pelilogiikkaan liittyvää.. Siellä olisi tarkoitus olla ainoastaan metodeita, jotka välittävät tiedon pelaajan siirrosta tekoälyille, ja vastaavasti tekoälyn siirron sitten takaisin käyttöliittymälle. Täytynee tutkia mikäli sinne on eksynyt jotakin muuta. 

Erittäin hyvä kommentti tuosta AI'na valintatavasta. Täytynee dokumentoida tarkemmin miten tuo valinta tehdään. Mutta tosiaan siis Game.Java luokassa getAIMove metodi pyytää jokaista AIntf luokan toteuttavaa tekoälyä kertomaan oman mielipiteensä siitä, mitä seuraavaksi pitäisi valita - ja valinta talletetaan eräänlaiseen Map-tyyliseen tietorakenteeseen, jossa valinnan painotus tulee tekoälyn voittoprosentin mukaan. Tämän jälkeen tehdään painotettu arvaus (eli esim jos 70% kaikista voteista on "kivi", niin painotetaan sitten valinta niin, että on 70% todennäköisyys, että kivi valitaan, jne.) käyttäen random - tyylistä algoritmiä, joka palauttaa arvon väliltä 0 - (Kaikkien votejen summa).
Olen jo vähän tuota getAIMove metodia pilkkonut osiin, ja jatkan pilkkomista vielä tulevina viikkoina.

Herokussa oleva versio on toistaiseksi vielä muutaman viikon vanha, eli se on vähän helpompi voittaa kun "live" versio, mutta silti vielä osittain arvattavissa. Tätä olisi ehkä voinut vielä hioa esimerkiksi muuttamalla eri tekoälyjen painotusta tuossa valintaprosessissa, mikäli aikaa olisi tuohon enempi.

En tosiaan tuosta Mac ja linux testaamista ole hirveästi päässyt vielä testaamaan ikävä kyllä, koska en omiosta omaa semmoista, mutta ilmeisesti ei siis myöskään projektin ajaminen k.o. käyttiksillä toimi. Todennäköisesti sen takia, että ChromeDriver joka projektissa löytyy on windows pohjainen, eli varmaan saisi toimimaan jos tietäisi ollenkaan millaisen sinne pitäisi ladata. Ehkä joskus sitten.

Olinkin ehtinyt tuon 11:15 jälkeen tuon statistiikan heittää omaan kansioonsa, mutta voisihan sitä vaikka kaikki raportit ja statistiikat YM laittaa yhteen kansioon, joka vielä vähän siivoisi repoa enempi. Tehdään tämä, kuulostaa järkevältä :)

Ja tosiaan Controllers luokkaa ei oltu kommentoitu, sillä idea oli se, että Controllers luokka vastaisi lähinnä tuosta UI'n puolesta, joka ei suoraan liity projektin skooppiin, joten en siihen käyttänyt aikaa.

En ole vielä päättänyt, että pitäisikö tekoälyille antaa jonkin sorttista ennakkodataa? Toistaiseksi alkuun tekoälyt eivät tiedä mitään mistään, ja oppivat pelatessaan enemmän pelaajan pelityylistä - eli mitä pidempään pelaa, sen todennäköisempää on, että tekoäly osaa arvata mitä ajattelet. Näin ainakin siis teoriassa ;)

**Comment by xTooth** [comment]
Top memes
